### PR TITLE
setup on local machine

### PR DESCRIPTION
**Pull request by varunKT001**
Added terminal screenshot

Issue: 1

#### Short description of what this resolves:
Setup this project on my local machine 

#### Changes proposed in this pull request and/or Screenshots of changes:
terminal ss : 
varunKT001

browser ss : 
image

### CODE REVIEW

**Comment by Mudit018** [comment]
You had to provide two images in folder

**Comment by varunKT001** [comment]
okk i will fix it

**Comment by varunKT001** [comment]
I have added the images in a seperate folder

**Comment by Mudit018** [comment]
You had to change only in on folder

**Comment by varunKT001** [comment]
🙂 wait let me change again

**Comment by varunKT001** [comment]
okk done, i hope its fine now 🙂👍

**Comment by Mudit018** [comment]
@varunKT001 Fork the repo again, it is showing that you have just renamed the files but still all those files are changed

**Comment by varunKT001** [comment]
ok

**Comment by varunKT001** [comment]
i will make a fresh pr

**Pull request closed without merging**
