### PR TITLE
Add transition between between components

### PR DESCRIPTION
**Pull request by batflarrow**
Issue: 144

#### Short description of what this resolves:
Added transition between compiler and dashboard components

#### Changes proposed in this pull request and/or Screenshots of changes:

- https://geek-editor-batflarrow.netlify.app/compiler
-
-

### CODE REVIEW

**Comment by batflarrow** [comment]
@Mudit018 Please review and let me know if any thing else is required.

**Comment by Mudit018** [comment]
@batflarrow Add some transition in navbar as well, rest everything is nice.

**Comment by Mudit018** [comment]
@batflarrow  Have you changed this file's CSS or your local repo isn't updated because the CSS of the below page has been updated.

image
image

**Comment by batflarrow** [comment]
> @batflarrow  Have you changed this file's CSS or your local repo isn't updated because the CSS of the below page has been updated.
> 
> image
> image
> 

Leme check whats the issue coz i just added three line to navbar. css

**Comment by batflarrow** [comment]
> @batflarrow Could you join **VC** on discord and show me the changes.

Yeah sure just a couple of minutes

**Pull request merged**
